### PR TITLE
added release script

### PR DESCRIPTION
**Pull request by meomancer**
hi @ismailsunni 
i'm not sure why
when on directly copy to plugins model, it is broken (no module xxxxx), but when i import cadasta as softlink, it is work

here is the released zip
[cadasta.1.0.0.alpha.zip](https://github.com/kartoza/cadasta-qgis-plugin/files/726031/cadasta.1.0.0.alpha.zip)

### CODE REVIEW

**Comment by Gustry** [comment]
What is the name of the module missing ?

**Comment by ismailsunni** [comment]
Hi @meomancer 

The problem is caused by the same name directory for the package.
So, the directory structure in your package is:
cadasta/cadasta/common/...

the plugin want to import logging like this: `from cadasta.common.custom_logging import setup_logger`

But, it won't find the common package in the first directory.

My suggestion would be change the package name directory to something like `cadasta-qgis-plugin`

**Comment by meomancer** [comment]
hi @ismailsunni 
thank you, it is working now
PR updated

**Review by dimasciput — APPROVED** [review]
LGTM

**Pull request merged**
