### PR TITLE
update translation framework

### LINKED ISSUE #40: Setup Translation Framework
We need to setup translation framework. I suggest to use Transifex for the translation tools. You can use this https://github.com/inasafe/inasafe/wiki/Internationalisation as reference.

### PR DESCRIPTION
**Pull request by meomancer**
fix #40 
I'm still using qt translation

### CODE REVIEW

**Review by timlinux — COMMENTED** [review]
LGTM

**Comment by meomancer** [comment]
Updated, fixed plugin isn't translated when qgis change it's locale

screenshot from 2016-12-23 12 55 43

**Comment by dimasciput** [comment]
LGTM

**Comment by ismailsunni** [comment]
Great @meomancer

**Pull request merged**
