### PR TITLE
questionnaire

### LINKED ISSUE #71: Add Questionnaire

### PR DESCRIPTION
**Pull request by meomancer**
partial fix #71 
- [x] get questionnaire
- [x] put questionnaire
- [x] generate json questonnaire object based on attributes name
- [x] generate json questonnaire object based on attributes type

other than will be announced

### CODE REVIEW

**Comment by meomancer** [comment]
Updated questionnaire
made UI for that with textbox so user can edit it manually

i think we can hide it and made this feature in update-project.
What it is done are:
- get available questionnaire
- if not available, made from default questionnaire and add new attributes and type
- if available, generate it based new attributes and type

new project:
screenshot from 2017-01-23 14 20 40

generated:
screenshot from 2017-01-23 14 21 12

After put:
selection_021

**Note:**
- now all of type is still using TX for new attributes
- when update in second times, it give 500

**Comment by meomancer** [comment]
Put questionnaire in create project:
selection_041
selection_042
selection_043
selection_044
selection_045
selection_046

**Comment by cchristelis** [comment]
LGTM

**Comment by meomancer** [comment]
updated:
remove questionnaire in update project
regarding with : https://github.com/kartoza/cadasta-qgis-plugin/issues/87

because generate questionnaire needs layer in memory, but update project doesn't download or use it

**Comment by dimasciput** [comment]
Hi @meomancer , can you fix the travis error then merge this PR

**Pull request merged**
