### PR TITLE
update UX

### LINKED ISSUE #72: UX Suggestions
After finishing upload, perhaps we can remove the notes under the progress bar since it gives different information with the one above the progress bar.
Perhaps we can also make the text or progress bar bigger to make it more readable and less wasting space.
screen shot 2017-01-05 at 07 32 18

Is it possible to not choose any field for the non-required one? If so, there should be an option to choose `no column` and set by default.
screen shot 2017-01-05 at 07 40 24

Trying to upload a project with the user and password in unit test. I got this error.
Perhaps, we can make the error message prettier.
screen shot 2017-01-05 at 07 40 50

### PR DESCRIPTION
**Pull request by meomancer**
this fix #72 
screenshot from 2017-01-24 11 36 42
screenshot from 2017-01-24 12 06 04
selection_022

### CODE REVIEW

**Comment by meomancer** [comment]
hi @ismailsunni, @Gustry 
i change QgsFieldComboBox to QComboBox in this PR because for adding empty options.
i already explore, it seems that i can't add empty options (or configuration for empty options) to QgsFieldComboBox
is there any way how to add this?

**Comment by Gustry** [comment]
You are right.
They added the option in QGIS 3 to allow an empty field : https://qgis.org/api/classQgsFieldComboBox.html#a84cebe4c4ef19364bfa0e7a43b55b70e

We will come back later. Thanks ;-)

**Comment by ismailsunni** [comment]
Hi @meomancer 
Looks great.
Can you replace the empty options with `No field` to make it more clear for the user?

**Comment by meomancer** [comment]
Updated:
screenshot from 2017-01-25 09 22 49

**Review by dimasciput — APPROVED** [review]
LGTM

**Review by Gustry — COMMENTED** [review]
Can you translate this string ?

**Comment by Gustry** [comment]
The 'no field'

**Pull request merged**
