### PR TITLE
Add cadasta to menu bar

### PR DESCRIPTION
**Pull request by dimasciput**
Based on the document, cadasta menu is in the menu bar.

screen shot 2016-12-20 at 4 44 15 pm

### CODE REVIEW

**Review by ismailsunni — APPROVED** [review]
LGTM

**Comment by timlinux** [comment]
I think if all we have is options in the submenu, it would be better in the settings menu on second thought. Otherwise it would be more sensible in the vector menu I think.

**Comment by Gustry** [comment]
I agree with Tim.
I don't really like when a plugin add new menu in the toolbar because it's not convenient if a lot of plugins are doing this way. Especially on mac where the space is limited.
I think if it's only options, the plugin menu is better. What will we have next in the menu ?

**Comment by dimasciput** [comment]
Based on the document there will be at least 4 submenu : 
- Create Project
- Upload Data to Existing Project
- Download Data from Cadasta
- Options/Settings

**Comment by ismailsunni** [comment]
What if we just put all of them in the toolbar? Is there any drawback?

**Comment by timlinux** [comment]
I think that goes against good HIG - the options will not be discoverable if the toolbar is not there....

I would prefer to see the menu go into the vector menu - it is very vector specific and we are trying to discourage people from putting things into the plugins menu.

**Comment by timlinux** [comment]
+ having a toolbar too would be good

**Pull request merged**
