### PR TITLE
Fix empty strings translated to None

### LINKED ISSUE #173: Blank strings are getting translated to "None"
When uploading a QGIS layer that has attributes that are blank somehow this is getting turned to "None"

See attached sample file

[kate_made_shp.zip](https://github.com/Cadasta/cadasta-qgis-plugin/files/959213/kate_made_shp.zip)

This is then causing a parsing error on the Cadasta side.

### PR DESCRIPTION
**Pull request by dimasciput**
Fix #173

### CODE REVIEW

**Comment by wonderchook** [comment]
@dimasciput I tested out this pull request fix. It doesn't seem to work in cases where you have a text field with a data string in it. I've attached a sample 

[kate_made_geojson.zip](https://github.com/Cadasta/cadasta-qgis-plugin/files/962499/kate_made_geojson.zip)

**Comment by dimasciput** [comment]
Thanks, I updated my PR. If you gave empty string for party name, the output will be like this : 
screen shot 2017-04-28 at 12 35 53 pm

**Comment by wonderchook** [comment]
I haven't tested this yet, but I think you fixed a different issue. What I think is happening is when you have a string column but happen to have data in it that parses to a date e.g. 2007-01-01. Somehow this is causing an issue on upload.

**Comment by dimasciput** [comment]
> I haven't tested this yet, but I think you fixed a different issue. What I think is happening is when you have a string column but happen to have data in it that parses to a date e.g. 2007-01-01. Somehow this is causing an issue on upload.

Well I managed to upload the project with no issue, here's a screenshot from cadasta site : 
screen shot 2017-05-02 at 10 50 18 am

**Comment by wonderchook** [comment]
Okay seems to be working now!

**Pull request merged**
